/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DemoInstanceUnityWrapper: typeof import('./src/components/DemoInstanceUnityWrapper.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadAndScanModelUnity: typeof import('./src/components/LoadAndScanModelUnity.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModelDiffUnity: typeof import('./src/components/ModelDiffUnity.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    TelemetryHistoryTable: typeof import('./src/components/TelemetryHistoryTable.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Vector3Data: typeof import('./src/components/Vector3Data.vue')['default']
    VisualizeModelUnity: typeof import('./src/components/VisualizeModelUnity.vue')['default']
  }
}
